### ISSUE TITLE
ReMo database too large, 3 options...

### ISSUE THREAD

**Issue by SeanMainer** [jparkington/Bookshelf-Scanner#16]
I added in a data folder to the repo this morning, and within it - tried to add, commit, push the database (in json) provided by ReMo (from Canvas >  > Files > Final Project > Database). However, when I attempted to push - got an error indicating db is >100MB so exceeds Git's file size limit of 100MB.
We have a few options to proceed - seeking opinions/ guidance:
1. Use Git's Large File Storage (LFS) - a "tool to keep large files in our repo while keeping a lightweight reference in our Git history"
2. Break it into smaller chunks less than 100MB
3. Store externally and reference otherwise.

Seems best option would be #1, but I am inexperienced with this, so curious of all of your thoughts?

**Comment by jparkington** [comment]
Closed by #17
